apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- pdb.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- name: controller
  newName: quay.io/rh-ee-dkushwah/llama-stack-k8s-operator
  newTag: sha256:50c94b99fe6ab9718427ad75d1fc0185ac57bfd1c1c29b37915863228c0f9d09
